apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: patrikassignment
spec:
  selector:
    app: hello
  ports:
    - name: hello
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP